name = "oidc-basic-trans-worker"
main = "src/index.js"
compatibility_date = "2022-08-01"

[vars]
AUTH0_DOMAIN = 
AUTH0_CLIENT_ID = 
AUTH0_CLIENT_SECRET = 
AUTH0_CALLBACK_URL = 
COOKIE_SECRET = 

FAAS_USER = 
FAAS_PASSWORD = 
